/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package restclt.lib

import spock.lang.Specification

class FeatureBuilderTest extends Specification {
//    def "someLibraryMethod returns true"() {
//        setup:
//        def lib = new FeatureBuilder()
//
//        when:
//        //def result =
//
//        then:
//        result == true
//    }
}
