/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package restclt.app

import restclt.client.RestClient
import restclt.client.httpclient4.HttpClient4RestClient
import restclt.client.Response

import static restclt.lib.ScriptBuilder.runWebFeature

class App {
    String getGreeting() {
        return 'Hello world.'
    }

    static void main(String[] args) {
        RestClient client = new HttpClient4RestClient()
        runWebFeature(new File("web-scenario.groovy"), client)
        //Response response = new HttpClient4RestClient().get()
        //println response.status
        //println response.headers
        //println response.body
    }
}
